---
language: node_js
node_js:
  - 0.12.7

sudo: false

branches:
  only: master

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - npm config set spin false
  - npm install -g npm@^2

install:
  - npm install -g codeclimate-test-reporter
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

after_script:
  - codeclimate-test-reporter < lcov.info

after_success:
  - ember build --environment production
  - openssl aes-256-cbc -K $encrypted_faf5e7d2acb0_key -iv $encrypted_faf5e7d2acb0_iv -in travis_rsa.enc -out travis_rsa -d
  - chmod 600 travis_rsa
  - mv travis_rsa ~/.ssh/id_rsa
  - scp -P $SCP_PORT -o stricthostkeychecking=no -r ./dist/. $SCP_USER@$SCP_IP:/var/www/gtfriender.com/.
