---
language: node_js
node_js:
  - "0.12.7"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g codeclimate-test-reporter
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

after_script:
  - codeclimate-test-reporter < lcov.info
